### ISSUE TITLE
"Launch PWCG" Function Not Working

### ISSUE THREAD

**Issue by Alt-Blu** [rafaelvcaetano/il2integrator#4]
I am running PWCG version 13.7.0 and IL2 Integrator version 1.1. IL2 Integrator does not "see" PWCG, and the launch option for it is greyed out. After some experimentation, I believe the issue to be a simple naming problem. PWCG recently changed its top level folder name from "PWCGCampaign" to "PWCGBoS".PWCG also changed the main exe from "PWCGBoS.exe." to "PWCG.exe". If I rename the folder and file manually in Windows, IL2 Integrator can launch PWCG without issue.

I believe your main code issue is in the following lines:

Line 20:
https://github.com/rafaelvcaetano/il2integrator/blob/49d04d94cbcb89ff02d53ec82e5eeec26c0ff7ef/service-pwcg/src/main/java/me/magnum/il2mapintegrator/pwcg/commands/StartPWCG.java#L20

and line 44:
https://github.com/rafaelvcaetano/il2integrator/blob/49d04d94cbcb89ff02d53ec82e5eeec26c0ff7ef/service-pwcg/src/main/java/me/magnum/il2mapintegrator/pwcg/commands/StartPWCG.java#L44

Log file attached for reference
[integrator-log.txt](https://github.com/rafaelvcaetano/il2integrator/files/7859167/integrator-log.txt)

**Comment by rafaelvcaetano** [comment]
Thanks for raising awareness regarding this problem and providing a detailed description. This issue should now be fixed in [version 1.2](https://github.com/rafaelvcaetano/il2integrator/releases/tag/v1.2).

**Comment by Alt-Blu** [comment]
> Thanks for raising awareness regarding this problem and providing a detailed description. This issue should now be fixed in [version 1.2](https://github.com/rafaelvcaetano/il2integrator/releases/tag/v1.2)

I can confirm version 1.2 does fix this issue. Thank you!
