### ISSUE TITLE
IL2 Tactical Map PWCG Campaign Integration Not Working

### ISSUE THREAD

**Issue by Alt-Blu** [rafaelvcaetano/il2integrator#5]
I am running PWCG version 13.7.0, IL2 Integrator version 1.1, and IL2 Tactical Map version 1.5.5. IL2 Tactical Map is unable to connect to PWCG created campaigns using IL2 Integrator. Please see attached screenshot and log for the exact nature of the error.

![IL2 TacMap Error_1](https://user-images.githubusercontent.com/97646480/149252046-b37c4720-5a27-41cb-894c-f75522a4c3cb.png)

[integrator-log_tacmapError.txt](https://github.com/rafaelvcaetano/il2integrator/files/7859216/integrator-log_tacmapError.txt)

I believe the issue to be as simple file path issue with the following line:
https://github.com/rafaelvcaetano/il2integrator/blob/49d04d94cbcb89ff02d53ec82e5eeec26c0ff7ef/service-pwcg/src/main/java/me/magnum/il2mapintegrator/pwcg/commands/ListCampaigns.java#L21

PWCG updated their file naming and structure for the campaign folder to the following:
"PWCGBoS\User\Campaigns"

**Comment by rafaelvcaetano** [comment]
Once again, thanks detailed description of the problem. This should also be fixed in [version 1.2](https://github.com/rafaelvcaetano/il2integrator/releases/tag/v1.2).

**Comment by Alt-Blu** [comment]
> Once again, thanks detailed description of the problem. This should also be fixed in [version 1.2](https://github.com/rafaelvcaetano/il2integrator/releases/tag/v1.2).

I can confirm version 1.2 does fix this issue. Thank you!
